basePath: /
info:
  contact: {}
  description: open-IM-Server 的API服务器文档, 文档中所有请求都有一个operationID字段用于链路追踪
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: open-IM-Server API
  version: "1.0"
paths: {}
swagger: "2.0"
